### PR TITLE
18 add extra kicad files to gitignore

### PR DESCRIPTION
**Pull request by DrewBrandt**
Fix for #18. Stopped tracking kicad backups, kicad autogen files, the .vscode folder, and .DS_Store. Also deleted all of these type of files form source control.

### CODE REVIEW

**Review by jhauerst — CHANGES_REQUESTED** [review]
Looks mostly good to me. I think you are right about the files with ~ being autosave files, but I found some ```~*.kicad_sch.lck``` files that were not picked up by the ```.gitignore```. Looking at the changes you made, I would expect them to, but see if you can find out why those were missed. For ignoring the backups folders, could you also include the ```Side_Projects``` folder in addition to the ```Spaceport``` folder? There are going to be some PCBs in there as well. After those two changes I think this should be ready to be merged.

**Comment by DrewBrandt** [comment]
Alright I believe those two issues have been addressed, and I added some _autosave files to it as well.

**Review by jhauerst — CHANGES_REQUESTED** [review]
Looks good. I saw you removed the extra kicad files from the ```Side_Projects``` folder, but could you also modify the ```.gitignore``` so that the rules for the ```*-backups``` and the ```_autosave*``` folders/files also apply to the ```Side_Projects``` folder? Right now they only apply to the ```Spaceport``` folder.

**Comment by DrewBrandt** [comment]
Bruh... I have too many local branches. Fixed.

**Review by jhauerst — APPROVED** [review]

**Pull request merged**
