### PR TITLE
45 fix data strings

### PR DESCRIPTION
**Pull request by DrewBrandt**
Fixes issue #45. I rewrote part of the State class and part of the sensor classes to use a `std::vector<String>` to manage the headers instead of the manually typed string concats before. I felt that would make the code much more readable (and therefore maintainable). 

As a direct fix for this issue, I added commas to the end of the data strings for each sensor so that appending more sensors on doesn't break it. I then remove the last trailing comma at the end.

Separate from this, I think that the logic of the state class should be rewritten away from multiple individual flags and move towards a map of sensors. Something like ` Map sensors<SensorType, *Sensor>` so you can do like `sensors[BAROMETER]` and get access to that sensor. We start by setting each sensor to `nullptr` so that we can check if that sensor is enabled by checking if it's equal to `nullptr` or not. This is a rough idea and I'm happy to do something else, but I feel the way it is now is a bit hard to maintain.

### CODE REVIEW

**Review by varun-un — CHANGES_REQUESTED** [review]
These look good, there's just a few comments I have. I don't know if you've tried building or compiling the code you modified for an Arduino or Teensy target, but I'm not sure that it would properly compile.

The Arduino framework doesn't natively support the use of the `std` namespace and its functions, which is why we can't use `Vector`s within the code. If you notice, anytime we want to do an array without explicit memory allocation, we use the `imumaths` library and its Vector template class, as that has been written explicitly for the Arduino platform. With this, I also don't fully know if `String` is completely supported by Arduino (for example, the `.isEmpty()` method was giving us an error from one of our libraries), so you'd have to test that more.

Also, gerber files are used for production, as we take the PCB design files, export them to gerbers, and send them to the manufacturer to produce, so I think those would still be worthwhile to source control. 

Other than that, I think the changes are good, and the idea of using a sensors array is a good one (it's why all sensor superclass types extend `Sensor`), but we'd have to test that implementation a bunch. This is good work though!

**Comment by DrewBrandt** [comment]
Interesting... I compiled it with Platformio and it had no complaints for me. Also, String is not from C++, it's from Arduino, so I certainly hope it works.

I'll add the gerbers back into the file on the other branch. I assumed they would be regenerated every time you needed them to avoid stale data and so would not want them in source control.

**Comment by DrewBrandt** [comment]
After reading more about it, I see that this method is probably not the best. It looks like it's possible that Platformio uses Teensyduino when compiling for Teensies, which includes expanded access to c++ features (like stl) compared to base Arduino. Still, there is more overhead involved with creating and manipulating vectors and Arduino Strings than there is with more basic types, so I might look in a way to make it more memory/cpu efficient tomorrow.

Having to think about memory and processor limitations to do basic string manipulation is weird.

**Review by jhauerst — CHANGES_REQUESTED** [review]
Looks mostly good to me. I do agree that we should probably avoid using ```std``` libraries where possible, so if you could switch to using the imumaths ```Vector``` or just a plain array that would probably be better. In terms of switching away from Arduino ```String```, I worked on that for the radio code since that needs to be able to compile on Raspberry Pi, so you can take a look at that for ideas. Off the top of my head, you could probably just replace the csvHeader variable with a ```char[]```, then just use ```strcat()``` to put all the headers together. Although, most of our code uses ```String``` and this doesn't need to run on a Pi, so it's probably fine if you just want to use ```String``` rather than dealing with c style strings.

Also for Arduino ```String```, I think they might have removed the ```isEmpty()``` method from the class a some point, because I'm pretty sure I remember using it. The library that caused the error probably just hadn't been updated yet, because we used it last year without issue.

I also noticed you added ```#include <numeric>``` to ```State.h```, but I couldn't find where it was used. Do you know where you used it and whether there are equivalent Arduino functions?

Also, I like the idea of the sensor map, it seems like an pretty elegant way of interacting with sensors, and makes sense to store all the sensors under one variable.

**Comment by DrewBrandt** [comment]
After doing some more research on what exactly the overhead of using `vector` and `std` in general are, I think the worry may be overblown. Unless we are worried about going to a less powerful processor, the Teensy should be more than capable of handling the extra couple of instructions and bytes associated with the memory management. That said, I believe I have an idea for moving to arrays instead that makes it not _easier_ but at least not harder. 

As for the Arduino String, I think moving away from that wouldn't be a bad idea. I would suggest `std::string` but if you really want to stay away from `std` then we would have to do some more work to work with `char[]`s. I noticed the `RecordData` library also has a reference to `<vector>` in `psram.h`.

I have no idea why I added `<numeric>` because removing it breaks nothing. _hmm..._

**Comment by DrewBrandt** [comment]
Alright this code should be in a currently working state, with the fix made to this issue. I am going to create a new issue that deals with the larger changes that get rid of Arduino `String` and C++ `std`. Unless there is an issue with the code itself, I believe this can be merged into main.

**Review by jhauerst — CHANGES_REQUESTED** [review]
Just a couple things. Can you merge main into this branch again to get the changes from #52? There's currently a merge conflict with the ```.gitignore```. Also, based on an earlier comment, if the ```<numeric>``` header isn't doing anything it's probably best to remove it. I think after those two things this should be good to merge.

**Comment by DrewBrandt** [comment]
Done. Should be good to go. The entire thing might be moot if you guys like the other branch though.

**Review by jhauerst — APPROVED** [review]

**Comment by varun-un** [comment]
So you're saying there's no issues with using `std::vector`? Unless I missed something, it doesn't seem to be in the Arduino.h libraries? Also, if it's from the `#include <vector>` that you're getting it, would you not need to include that in each of the header files?

**Comment by jhauerst** [comment]
> So you're saying there's no issues with using `std::vector`? Unless I missed something, it doesn't seem to be in the Arduino.h libraries? Also, if it's from the `#include <vector>` that you're getting it, would you not need to include that in each of the header files?

I tried compiling it myself and everything worked fine. I'm not completely sure why it works, because I also thought std libraries were not supported on Arduino, but this could be a possible explanation:

> It looks like it's possible that Platformio uses Teensyduino when compiling for Teensies, which includes expanded access to c++ features (like stl) compared to base Arduino.

But, since it successfully compiles, I would assume there should be no issues, though I haven't had a chance to test it. 

In terms of having ```#include <vector>``` in each of the sensor header files, since vector is included in ```Sensor.h```, and all the sensors include ```Sensor.h```, they all have access to it.

**Comment by DrewBrandt** [comment]
Based on my reading, the C++ STL is not supported by base Arduino because many of the smaller, less powerful boards do not have the resources to effectively use it. The Teensies (and, from what it looked like to me, most boards that you would use in this kind of application) are equipped with much more processing power and memory than those boards and so when using the Teensy specific builds in Platformio, it includes access to those.

If everyone that we are writing code for is going to be using at least a teensy, or a more powerful STM32, then including classes from the standard library shouldn't be an issue.


All of that said, everything in this pull request can be superseded by everything on branch [54](https://github.com/Terrapin-Rocket-Team/SRAD_Avionics/tree/54-Remove-External-Refrences). Please have a look at that code. It has been tested to work better than (read: fixes this issue) the main branch code when fed with fake data from a previous launch.

**Comment by DrewBrandt** [comment]
Closing due to superseding by #54

**Pull request closed without merging**
